DROP DATABASE IF EXISTS music_db;
CREATE DATABASE music_db;

USE music_db;

CREATE TABLE Artist (
    ArtistID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ArtistName VARCHAR(100) NOT NULL
);

CREATE TABLE Genre (
    GenreID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    GenreName VARCHAR(50) NOT NULL,
    ArtistID INT NOT NULL,
    FOREIGN KEY (ArtistID) REFERENCES Artist(ArtistID)
);

CREATE TABLE Year (
    YearID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    YearValue INT NOT NULL
);

CREATE TABLE Album (
    AlbumID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AlbumTitle VARCHAR(100) NOT NULL,
    ArtistID INT NOT NULL,
    YearID INT NOT NULL,
    FOREIGN KEY (ArtistID) REFERENCES Artist(ArtistID),
    FOREIGN KEY (YearID) REFERENCES Year(YearID)
);

CREATE TABLE Song (
    SongID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SongTitle VARCHAR(100) NOT NULL,
    ArtistID INT NOT NULL,
    YearID INT NOT NULL,
    FOREIGN KEY (ArtistID) REFERENCES Artist(ArtistID),
    FOREIGN KEY (YearID) REFERENCES Year(YearID)
);